### ISSUE TITLE
windows support / build

### ISSUE THREAD

**Issue by maddin200** [gotranspile/cxgo#58] opened 2022-10-16 12:18 UTC
add support for Windows

**Comment by dennwc** [comment] 2022-10-16 12:43
You should provide some details here. Any specific errors you encountered? On which version? Is it a duplicate of #51?

**Comment by maddin200** [comment] 2022-10-16 12:52
Thanks. 
if possible pure windows support without cygwin (Windows 10)

**Closed** 2022-11-13 08:49 UTC
